# Fichier généré automatiquement par generate_inventory.sh — NE PAS ÉDITER À LA MAIN
# Régénérer avec : ./generate_inventory.sh

[front]
front ansible_host=35.181.4.173 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/todo-medishop-key.pem

[back]
back ansible_host=10.0.2.133 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/todo-medishop-key.pem

[db]
db ansible_host=10.0.2.238 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/todo-medishop-key.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
bastion_host=35.181.4.173
front_private_ip=10.0.1.111
